install:
  - cinst pandoc
  - cinst brew
  - brew install aspell
  - Choco list packagename --all

build: false

test_script:
  - ps: .\topdf.ps1

artifacts:
  - path: The-Return-of-Tom-Thumb.epub
    name: is_book_yeah
    type: file