install:
  - cinst pandoc
  - python -m pip install --upgrade pip
  - pip install -U pyenchant 
  - pip install -U nltk
  - python -m nltk.downloader all

build: false

test_script:
  - ps: .\topdf.ps1

artifacts:
  - path: The-Return-of-Tom-Thumb.epub
    name: is_book_yeah
    type: file
