install:
  - cinst pester

build: 
  - ps: write-host "building book"
  - ps: & .\_toolz\topdf.ps1

test_script:
  - ps: gci -r The-Return-of-Tom-Thumb.pdf

artifacts:
  - path: .\The-Return-of-Tom-Thumb.pdf
    name: is_book_yeah