install:
  - cinst pandoc
  - python -m pip install --upgrade pip #for spelling and theasurus
  - pip install -U pyenchant #for spelling
  - pip install -U nltk #for theasurus
  - python -m nltk.downloader all #for theasurus *** VERY SLOW ***
  - pip install gTTS #google text to speech

build: false

test_script:
  - ps: .\topdf.ps1

artifacts:
  - path: Chapter-Two-Spelling.txt
    name: spelling-errors-two
    type: file
  - path: Chapter-One-Spelling.txt
    name: spelling-errors-one
    type: file
  - path: Chapter-One-Words.txt
    name: word-matix
    type: file
  - path: The-Return-of-Tom-Thumb.epub
    name: is_book_yeah
    type: file
  - path: The-Return-of-Tom-Thumb.md
    name: is_book_yeah_md
    type: file
  - path: The-Return-of-Tom-Thumb.txt
    name: is_book_yeah_txt
    type: file
  - path: The-Return-of-Tom-Thumb.html
    name: is_book_yeah_html
    type: file
  - path: The-Return-of-Tom-Thumb.mp3
    name: is_book_yeah_mp3
    type: file

    