install:
  - ps: cat ".\TheKnight\the-knight-thumbnail.txt"
  - cinst pandoc
  - REM cinst lame
  - SET WANTTHES=0
  - copy LameExe/lame_v3.100.exe
  - rename lame_v3.100.exe lame.exe
  - dir
  - cinst sox.portable
  - python -m pip install --upgrade pip #for spelling and theasurus
  - pip install -U pyenchant #for spelling
  - pip install gTTS #google text to speech
  - IF "%WANTTHES%" == "1" pip install -U nltk #for theasurus
  - IF "%WANTTHES%" == "1" python -m nltk.downloader all #for theasurus *** VERY SLOW ***
  
build: false

test_script:
  - ps: .\topdf.ps1
  - ps: cat ".\Croconocerous\croco_on_mostly_blank_except_some_grass_man.txt"

artifacts:
  - path: Chapter-*-Spelling.txt
    name: spelling-errors
    type: file
  - path: Chapter-*-Words.txt
    name: word-matix
    type: file
  - path: The-Return-of-Tom-Thumb*.epub
    name: is_book_yeah
    type: file
  - path: The-Return-of-Tom-Thumb*.md
    name: is_book_yeah_md
    type: file
  - path: The-Return-of-Tom-Thumb*.txt
    name: is_book_yeah_txt
    type: file
  - path: The-Return-of-Tom-Thumb*.html
    name: is_book_yeah_html
    type: file
  - path: The-Return-of-Tom-Thumb*.mp3
    name: is_book_yeah_mp3
    type: file
  - path: The-Return-of-Tom-Thumb*.mp3.log
    name: is_book_yeah_mp3_log
    type: file
  - path: The-Return-of-Tom-Thumb-with-music*.mp3
    name: is_book_yeah_mp3_w_music
    type: file
  - path: A_Croconossorus_Tale.mp3
    name: is_croconossorus_real
    type: file
  - path: testymctestface.mp3
    name: testy_mc_testface
    type: file

on_success:
  - git clone https://github.com/PunkUnicorn/The-Return-Of-Tom-Thumb-Redirect-Static-Page.git
  - git config --global credential.helper wincred
  - cd ./The-Return-Of-Tom-Thumb-Redirect-Static-Page
  - ./getindex.cmd
  - REM git config --global user.email "%APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%"
  - REM git config --global user.name "%APPVEYOR_REPO_COMMIT_AUTHOR%"
  - git add ./public/index.html
  - git commit -m "Auto update"
  - git push
