install:
  - cinst pandoc
  - pip install -U pyenchant --version 10.0.1
 

build: false

test_script:
  - ps: .\topdf.ps1

artifacts:
  - path: The-Return-of-Tom-Thumb.epub
    name: is_book_yeah
    type: file
