install:
  - cinst pandoc
  - python -m pip install --upgrade pip #for spelling and theasurus
  - pip install -U pyenchant #for spelling
  - pip install -U nltk #for theasurus
  - python -m nltk.downloader all #for theasurus *** VERY SLOW ***

build: false

test_script:
  - ps: .\topdf.ps1

artifacts:
  - path: Chapter-One-Words.txt
    name: word-matix
    type: file
  - path: The-Return-of-Tom-Thumb.epub
    name: is_book_yeah
    type: file
